"""empty message

Revision ID: 34632f6ef3ed
Revises: 
Create Date: 2022-11-11 14:38:28.303488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34632f6ef3ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_do')
    # ### end Alembic commands ###
